server:
  port: 8005
spring:
  application:
    name: ATTENDENCE
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: Saiteja@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always
#
#resilience4j:
#  retry:
#    instances:
#      Account-service:
#        max-attempts: 3
#        wait-duration: 10s